# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: node:10
      user: node
restore_prepared_repo: &restore_prepared_repo
  - attach_workspace:
      at: ~/repo

version: 2
jobs:
  prepare:
    <<: *defaults
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          name: Restore Npm Package Cache
          keys:
            - npm-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn
      - save_cache:
          name: Save Npm Package Cache
          key: npm-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn  
      - persist_to_workspace:
          root: ~/repo
          paths:
            - '*'

  lint-code:
    <<: *defaults
    steps:
      - <<: *restore_prepared_repo
      - run:
          name: Lint code
          command: yarn run lint:code
  lint-styles:
    <<: *defaults
    steps:
      - <<: *restore_prepared_repo
      - run:
          name: Lint styles
          command: yarn run lint:styles          
  compile-dryrun:
    <<: *defaults
    steps:
      - <<: *restore_prepared_repo
      - run:
          name: Compilation Dry-Run
          command: yarn compile-dryrun
  test:
    <<: *defaults
    steps:
      - <<: *restore_prepared_repo
      - run:
          name: Run tests
          command: yarn test
  build-page:
    <<: *defaults
    steps:
      - <<: *restore_prepared_repo
      - run:
          name: Build the homepage
          command: yarn build
  build-storybook:
    <<: *defaults
    steps:
      - <<: *restore_prepared_repo
      - run:
          name: Build the storybook
          command: yarn build-storybook
  run-lighthouse:
    working_directory: ~/repo
    docker:
      - image: circleci/node:12-browsers
        user: node
    steps:
      - <<: *restore_prepared_repo
      - run:
          name: Run Lighthouse SEO checks
          command: yarn lighthouse
workflows:
  version: 2
  ci:
    jobs:
      - prepare
      - run-lighthouse:
          requires:
            - prepare
      - lint-code:
          requires:
            - prepare
      - lint-styles:
          requires:
            - prepare
      - test:
          requires:
            - prepare
      - build-page:
          requires:
            - prepare
      - build-storybook:
          requires:
            - prepare
      - compile-dryrun:
          requires:
            - prepare

