backend:
  name: git-gateway
  repo: hardforkio/homepage
  branch: feature/issue-91-create-team-section

locales: &locales
  options:
    - "en"
    - "de"

socialMediaPlatforms: &socialMediaPlatforms
  options:
    - "github"
    - "linkedIn"

media_folder: "static/img"
public_folder: "/img"
publish_mode: "editorial_workflow"

collections:
  - name: "imprint"
    label: "Imprint"
    delete: false
    files:
      - file: "src/data/imprint/imprint.json"
        name: "imprint"
        label: "Imprint"
        format: "json"
        identifier_field: "id"
        fields:
          - name: "id"
            label: "Identifier"
            description: "A name to identify this object within this collection. Should be unique within the collection."
            widget: "hidden"
            default: "Impressum"

          - name: "translations"
            label: "translations"
            widget: "list"
            fields:
              - { name: "locale", widget: "select", <<: *locales }
              - { name: "headline", widget: "string" }
              - { name: "subHeadline", widget: "string" }
              - { name: "metaTitle", widget: "string" }
              - { name: "content", widget: "markdown" }

  - name: "faqPage"
    label: "FaqPage"
    files:
      - file: "src/data/faqEntry/faq.json"
        format: "json"
        name: "faq"
        label: "FAQ"
        fields:
          - name: "id"
            label: "id"
            description: "A name to identify this object within this collection. Should be unique within the collection."
            widget: "string"
          - name: "translations"
            label: "translations"
            widget: "list"
            fields:
              - { name: "locale", widget: "select", <<: *locales }
              - { name: "headline", widget: "string" }
              - { name: "subheadline", widget: "string" }
              - { name: "metaTitle", widget: "string" }
              - name: "faqEntries"
                widget: "list"
                fields:
                  - { name: "question", widget: "string" }
                  - { name: "answer", widget: "markdown" }

  - name: "home"
    label: "Landing Page"
    delete: false
    files:
      - file: "src/data/home/home.json"
        name: "home"
        label: "Landing Page"
        format: "json"
        fields:
          - name: "id"
            label: "Identifier"
            description: "A name to identify this object within this collection. Should be unique within the collection."
            widget: "hidden"
            default: "home"

          - name: "translations"
            label: "translations"
            widget: "list"
            fields:
              - name: "locale"
                widget: "select"
                <<: *locales

              - name: "title"
                widget: "string"
                label: "Page title"
                description: "Title shown on top of page. Not an ID."

              - name: "heading"
                widget: "string"

              - name: "contactHeadline"
                widget: "string"
                description: "Contact Section Headline"

              - name: "contactDescription"
                widget: "string"

              - name: "contactButton"
                widget: "string"

              - name: "contactEmail"
                widget: "string"

              - name: "metaTitle"
                widget: "string"

              - name: "metaDescription"
                widget: "string"

              - name: "offerings"
                label: "Offerings"
                widget: "list"
                fields:
                  - { name: "headline", widget: "string" }
                  - { name: "image", widget: "image", allow_multiple: false }
                  - { name: "text", widget: "text" }

  - name: "team section"
    label: "team section"
    delete: false
    create: true
    identifier_field: "id"
    files:
      - file: "src/data/team/team.json"
        name: "team"
        label: "team"
        format: "json"
        identifier_field: "id"
        fields:
          - name: "id"
            widget: "string"
            default: "team section"

          - name: "translations"
            widget: "list"
            fields:
              - name: "locale"
                widget: "select"
                <<: *locales
              - name: "headline"
                widget: "string"
              - name: "subHeadline"
                widget: "string"
              - name: "footer"
                widget: "string"

          - name: "team members"
            widget: "relation"
            collection: "team member"
            searchFields: ["full name"]
            valuleField: "full name"

  - name: "team member"
    label: "team member"
    folder: "src/data/team/member"
    format: "json"
    identifier_field: "id"
    create: true
    fields:
      - name: "id"
        label: "full name"
        widget: "string"
      - name: "job title"
        widget: "string"
      - name: "degree"
        widget: "string"
      - name: "avatar"
        widget: "image"
      - name: "social media"
        widget: "list"
        fields:
          - name: "platform"
            widget: "select"
            <<: *socialMediaPlatforms
          - name: "user name"
            widget: "string"
