backend:
  name: git-gateway
  repo: hardforkio/homepage

media_folder: "static/img"
public_folder: "/img"
publish_mode: "editorial_workflow"

locales: &locales
  options:
    - "en"
    - "de"

socialMediaPlatforms: &socialMediaPlatforms
  options:
    - "github"
    - "linkedIn"

collections:
  - name: "imprint"
    label: "Imprint"
    delete: false
    files:
      - file: "src/data/imprint/imprint.json"
        name: "imprint"
        label: "Imprint"
        format: "json"
        identifier_field: "id"
        fields:
          - name: "id"
            widget: "hidden"
            default: "Impressum"

          - name: "translations"
            label: "translations"
            widget: "list"
            fields:
              - name: "locale"
                widget: "select"
                <<: *locales
              - name: "value"
                widget: "object"
                fields:
                  - { name: "headline", widget: "string" }
                  - { name: "subHeadline", widget: "string" }
                  - { name: "content", widget: "markdown" }

          - name: "head"
            label: "Head"
            widget: "object"
            fields:
              - { name: "title", widget: "localizedString" }
              - name: "meta"
                widget: "object"
                fields:
                  - { name: "description", widget: "localizedString" }
                  - { name: "keywords", widget: "localizedString" }

  - label: "FAQ Page"
    name: "faqPage"
    files:
      - file: "src/data/faqEntry/faq.json"
        format: "json"
        name: "faq"
        label: "FAQ"
        identifier_field: "id"
        fields:
          - name: "id"
            widget: "hidden"
            default: "faqPage"

          - name: "headline"
            widget: "localizedString"

          - name: "subheadline"
            widget: "localizedString"

          - name: "faqEntries"
            widget: "list"
            default: []
            identfier_field: "id"
            fields:
              - label: "Title"
                name: "id"
                widget: "string"

              - name: "translations"
                widget: "list"
                fields:
                  - name: "locale"
                    widget: "select"
                    <<: *locales
                  - name: "value"
                    widget: "object"
                    fields:
                      - { name: "question", widget: "string" }
                      - { name: "answer", widget: "markdown" }

          - name: "head"
            label: "Head"
            widget: "object"
            fields:
              - name: "title"
                widget: "localizedString"
              - name: "meta"
                widget: "object"
                fields:
                  - { name: "description", widget: "localizedString" }
                  - { name: "keywords", widget: "localizedString" }

  - name: "home"
    label: "Landing Page"
    delete: false
    files:
      - file: "src/data/home/home.json"
        name: "home"
        label: "Landing Page"
        format: "json"
        identifier_field: "id"
        fields:
          - name: "id"
            widget: "hidden"
            default: "home"

          - name: "contactEmail"
            widget: "string"

          - name: "heroHeadline"
            widget: "localizedString"
            label: "Page title"
            description: "Title shown on top of page. Not an ID."

          - name: "heroSubheadline"
            widget: "localizedString"

          - name: "contactHeadline"
            widget: "localizedString"
            description: "Contact Section Headline"

          - name: "contactDescription"
            widget: "localizedString"

          - name: "contactButtonText"
            widget: "localizedString"

          - name: "moreLinkText"
            widget: "localizedString"

          - name: "emailButton"
            widget: "localizedString"

          - name: "projectsHeadline"
            widget: "localizedString"

          - name: "offerings"
            label: "Offerings"
            widget: "list"
            default: []
            identfier_field: "id"
            fields:
              - label: "Title"
                name: "id"
                widget: "string"

              - name: "translations"
                label: "translations"
                widget: "list"
                fields:
                  - name: "locale"
                    widget: "select"
                    <<: *locales
                  - name: "value"
                    widget: "object"
                    fields:
                      - { name: "headline", widget: "string" }
                      - {
                          name: "image",
                          widget: "image",
                          allow_multiple: false,
                        }
                      - { name: "text", widget: "text" }

          - label: "Team"
            name: "team"
            widget: "object"
            hint: "Only shows after adding a team member."
            fields:
              - label: "Headline"
                name: "header"
                widget: "localizedString"

              - label: "Subheadline"
                name: "subheader"
                widget: "localizedString"

              - label: "Footer"
                name: "footer"
                widget: "localizedString"

              - label: "Team Members"
                name: "members"
                widget: "list"
                fields:
                  - label: "Member ID"
                    name: "uuid"
                    widget: "uuid"

                  - label: "Full Name"
                    name: "name"
                    widget: "string"

                  - label: "Job Title"
                    name: "jobTitle"
                    widget: "localizedString"

                  - label: "Degree"
                    name: "degree"
                    widget: "localizedString"

                  - label: "Avatar"
                    name: "avatar"
                    widget: "image"
                    allow_multiple: false

                  - label: "Social Media"
                    name: "socialMedia"
                    widget: "list"
                    fields:
                      - label: "Platform"
                        name: "platform"
                        widget: "select"
                        <<: *socialMediaPlatforms

                      - label: "Username"
                        name: "username"
                        widget: "string"

          - name: "head"
            label: "Head"
            widget: "object"
            fields:
              - { name: "title", widget: "localizedString" }
              - name: "meta"
                widget: "object"
                fields:
                  - { name: "description", widget: "localizedString" }
                  - { name: "keywords", widget: "localizedString" }

  - name: "footer"
    label: "Footer"
    delete: false
    files:
      - file: "src/data/footer/footer.json"
        name: "footer"
        label: "Footer"
        format: "json"
        identifier_field: "id"
        fields:
          - name: "id"
            widget: "hidden"
            default: "Footer"

          - label: "Imprint Link Text"
            name: "imprintLinkText"
            widget: "localizedString"

          - label: "Github Link URL"
            name: "githubLinkURL"
            widget: "string"

          - label: "Contact Email"
            name: "contactEmail"
            widget: "string"

          - label: "Copyright Text"
            name: "copyrightText"
            widget: "string"

  - name: "navbar"
    label: "Navbar"
    delete: false
    files:
      - file: "src/data/navbar/navbar.json"
        name: "navbar"
        label: "Navbar"
        format: "json"
        identifier_field: "id"
        fields:
          - name: "id"
            widget: "hidden"
            default: "navbar"

          - name: "translations"
            label: "translations"
            widget: "list"
            fields:
              - name: "locale"
                widget: "select"
                <<: *locales
              - name: "value"
                widget: "object"
                fields:
                  - name: "contactLinkText"
                    widget: "string"

                  - name: "FAQLinkText"
                    widget: "string"

  - name: "technology"
    label: "Technology"
    folder: "src/data/technology"
    create: true
    delete: false
    format: "json"
    identifier_field: "name"
    editor:
      preview: false
    fields:
      - label: "Tech ID"
        name: "uuid"
        widget: "uuid"
      - { label: "Name", name: "name", widget: "string", required: true }
      - { label: "Link", name: "link", widget: "string", required: false }

  - name: "project"
    label: "Project"
    folder: "src/data/project"
    identifier_field: "title"
    create: true
    format: "json"
    fields:
      - { label: "Title", name: "title", widget: "string", default: "project" }

      - { name: "slug", widget: "string" }

      - label: "Used technologies"
        name: "usedTechnologies"
        widget: "relation"
        collection: "technology"
        searchFields: ["name"]
        valueField: uuid
        displayFields: ["name"]
        multiple: true

      - name: "translations"
        label: "translations"
        widget: "list"
        fields:
          - name: "locale"
            widget: "select"
            <<: *locales
          - name: "value"
            widget: "object"
            fields:
              - { name: "client", widget: "string" }
              - { name: "clientLink", widget: "string" }
              - { name: "reference", widget: "string" }
              - {
                  name: "image",
                  widget: "image",
                  allow_multiple: false,
                  required: false,
                }
              - { name: "product", widget: "string" }
              - { name: "application", widget: "markdown" }
              - { name: "responsibilities", widget: "markdown" }

      - name: "head"
        label: "Head"
        widget: "object"
        fields:
          - { name: "title", widget: "localizedString" }
          - name: "meta"
            widget: "object"
            fields:
              - { name: "description", widget: "localizedString" }
              - { name: "keywords", widget: "localizedString" }
