backend:
  name: git-gateway
  repo: hardforkio/homepage
  branch: master

media_folder: "static/img"
public_folder: "/img"
publish_mode: editorial_workflow

collections:
  - name: "imprint"
    label: "Imprint"
    delete: false
    files:
      - file: "src/data/imprint/imprint.json"
        name: "imprint"
        label: "Imprint"
        format: "json"
        fields:
          - name: "title"
            label: "Short name"
            description: "A name to identify this object within this collection. Should be unique within the collection."
            widget: "hidden"
            default: "Impressum"

          - name: "translations"
            label: "translations"
            widget: "list"
            fields:
              - { name: "locale", widget: "select", options: ["en", "de"] }
              - { name: "headline", widget: "string" }
              - { name: "subHeadline", widget: "string" }
              - { name: "metaTitle", widget: "string" }
              - { name: "content", widget: "markdown" }
  - name: "faqEntry"
    label: "FaqEntry"
    folder: "src/data/faqEntry"
    create: true
    format: "json"
    fields:
      - name: "title"
        label: "title"
        description: "A name to identify this object within this collection. Should be unique within the collection."
        widget: "string"
      - name: "translations"
        label: "translations"
        widget: "list"
        fields:
          - { name: "locale", widget: "select", options: ["en", "de"] }
          - { name: "question", widget: "string" }
          - { name: "answer", widget: "string" }
