backend:
  name: git-gateway
  repo: hardforkio/homepage
  branch: master

media_folder: "static/img"
public_folder: "/img"
publish_mode: editorial_workflow

collections:
  - name: "imprint"
    label: "Imprint"
    delete: false
    files:
      - file: "src/data/imprint/imprint.json"
        name: "theImprint"
        label: "Imprint"
        format: "json"
        fields:
          - name: "translations"
            label: "translations"
            widget: "list"
            fields:
              - { name: "locale", widget: "select", options: ["en", "de"] }
              - { name: "headline", widget: "string" }
              - { name: "subHeadline", widget: "string" }
              - { name: "metaTitle", widget: "string" }
              - { name: "content", widget: "markdown" }
